#!/usr/bin/env python3

import markdown
import re
import sys

mdexts = ['markdown.extensions.tables', 'markdown.extensions.toc(baselevel=2)']

head = '''<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{0}</title>
    <link type="text/css" rel="stylesheet" href="style.css"/>
</head>
'''

tail = '''</body>
</html>
'''

if len(sys.argv) != 3:
    print('*** Usage: make-doc <src> <dst>')
    sys.exit(1)

src=sys.argv[1]
dst=sys.argv[2]

with open(src, 'r', encoding='utf-8') as s:
    md = s.read()

lines = md.splitlines()
title = lines[0].strip('# ')
title = re.sub(r'\[([^()\[\]]+)\]\([^()\[\]]+\)', r'\1', title)
html = head.format(title)
html += markdown.markdown(md, extensions=mdexts)
html += tail

with open(dst, 'w', encoding='utf-8') as d:
    d.write(html)
